import React, { useMemo, useEffect, useRef } from 'react';
import { initAudio, playNote } from '../utils/playback';
import { NOTE_NAMES } from '../utils/music';

function midiToLabel(midi) {
  const names = NOTE_NAMES || ['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
  return names[midi % 12] || '?';
}

// Build a raw ASCII tab string from columns
export function buildAsciiTab(columns, tuningLabels = ['e', 'B', 'G', 'D', 'A', 'E']) {
  const strings = [0, 1, 2, 3, 4, 5];
  let percLine = 'Perc|';
  const stringLines = strings.map(s => `${tuningLabels[s]}   |`);

  columns.forEach(col => {
    // Bar line
    if (col.type === 'barline') {
      percLine += '|';
      stringLines.forEach((_, i) => { stringLines[i] += '|'; });
      return;
    }

    let maxWidth = 3;
    const cellRep = {};
    let percRep = '';

    if (col.type === 'melody' || col.type === 'chord' || col.type === 'spacer') {
      strings.forEach(sIdx => {
        const note = col.notes?.find(n => n.stringIdx === sIdx && !n.isPerc);
        if (note) {
          let chunk = `${note.fretIdx}`;
          if (note.tech === '<>') chunk = `<${chunk}>`;
          else if (note.tech === '()') chunk = `(${chunk})`;
          if (note.techLabel) chunk = `${chunk}${note.techLabel}`;
          cellRep[sIdx] = chunk;
          if (chunk.length + 1 > maxWidth) maxWidth = chunk.length + 1;
        }
      });
      const percs = col.notes?.filter(n => n.isPerc || n.stringIdx === 'perc');
      if (percs?.length > 0) {
        percRep = percs.map(p => {
           if (p.tech === 'kick' || p.techLabel === 'K') return 'K';
           if (p.tech === 'snare' || p.techLabel === 'S') return 'S';
           return 'x';
        }).join('');
        if (percRep.length + 1 > maxWidth) maxWidth = percRep.length + 1;
      }
    }

    if (col.type === 'repeat_start') { percLine += '|:-'; }
    else if (col.type === 'repeat_end') { percLine += '-:|'; }
    else if (col.type === 'label') { percLine += '---'; }
    else if (percRep !== '') {
      let p = `-${percRep}`; while (p.length < maxWidth + 1) p += '-'; percLine += p;
    } else { percLine += '-'.repeat(maxWidth + 1); }

    strings.forEach((sIdx, i) => {
      let chunk = cellRep[sIdx] || '';
      let padded = '';
      if (col.type === 'repeat_start') padded = '|:-';
      else if (col.type === 'repeat_end') padded = '-:|';
      else if (col.type === 'label') padded = '---';
      else {
        if (chunk !== '') { padded = `-${chunk}`; while (padded.length < maxWidth + 1) padded += '-'; }
        else { padded = '-'.repeat(maxWidth + 1); }
      }
      stringLines[i] += padded;
    });
  });

  percLine += '|';
  stringLines.forEach((_, i) => { stringLines[i] += '|'; });

  return [percLine, ...stringLines].join('\n');
}

/**
 * Trigger a print dialog for PDF export.
 */
export function exportAsPdf(columns, title = 'TabCraft Tab') {
  const ascii = buildAsciiTab(columns);
  const printWindow = window.open('', '_blank', 'width=900,height=700');
  if (!printWindow) { alert('Allow popups to export PDF.'); return; }
  printWindow.document.write(`
    <!DOCTYPE html><html><head>
    <title>${title}</title>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Courier+Prime:wght@400;700&family=Inter:wght@400;700&display=swap');
      * { box-sizing: border-box; margin: 0; padding: 0; }
      body { background: #fff; color: #111; font-family: 'Inter', sans-serif; padding: 40px; }
      h1 { font-size: 22px; font-weight: 700; margin-bottom: 6px; }
      p.meta { font-size: 12px; color: #666; margin-bottom: 24px; }
      pre { font-family: 'Courier Prime', 'Courier New', monospace; font-size: 13px; 
            line-height: 1.8; letter-spacing: 0.02em; white-space: pre; overflow-x: auto;
            background: #f8f8f8; border: 1px solid #ddd; border-radius: 8px; padding: 20px; }
      .footer { margin-top: 24px; font-size: 11px; color: #aaa; }
      @media print {
        body { padding: 20px; }
        pre { page-break-inside: avoid; border: 1px solid #ccc; }
      }
    </style>
    </head><body>
    <h1>🎸 ${title}</h1>
    <p class="meta">Generated by TabCraft — ${new Date().toLocaleDateString()}</p>
    <pre>${ascii}</pre>
    <p class="footer">TabCraft — Percussive Fingerstyle Guitar Editor</p>
    <script>window.onload = function(){ window.print(); }<\/script>
    </body></html>
  `);
  printWindow.document.close();
}

// ── Component ──────────────────────────────────────────────────────────────

export default function TabViewer({
  columns = [], setColumns, editable = false, onColSelect,
  activeCol, playingCol,
  confidenceScores = {},
  activeLayer = 'all',
  tuning = [64, 59, 55, 50, 45, 40],
  capo = 0,
}) {
  const strings = [0, 1, 2, 3, 4, 5]; 
  const tuningLabels = tuning.map(midi => midiToLabel(midi));

  const COLUMNS_PER_ROW = 48;

  const handleDelete = (index) => {
    setColumns(prev => prev.filter((_, i) => i !== index));
    if (onColSelect) onColSelect(null);
  };

  const handleAddBefore = (index) => {
    setColumns(prev => {
       const clone = [...prev];
       clone.splice(index, 0, { id: `col-spc-${Date.now()}-${Math.random()}`, type: 'spacer', notes: [] });
       return clone;
    });
    if (onColSelect) onColSelect(null);
  };

  const handleAddAfter = (index) => {
    setColumns(prev => {
       const clone = [...prev];
       clone.splice(index + 1, 0, { id: `col-spc-af-${Date.now()}-${Math.random()}`, type: 'spacer', notes: [] });
       return clone;
    });
    if (onColSelect) onColSelect(null);
  };

  const handleSetLabel = (index) => {
    const text = prompt("Enter section label (e.g. Verse, Chorus):");
    if (!text) return;
    setColumns(prev => {
       const clone = [...prev];
       clone.splice(index, 0, { id: `col-lbl-${Date.now()}-${Math.random()}`, type: 'label', text });
       return clone;
    });
    if (onColSelect) onColSelect(null);
  };

  const handleSetRepeat = (index, type) => {
    setColumns(prev => {
       const clone = [...prev];
       clone.splice(index, 0, { id: `col-rpt-${Date.now()}-${Math.random()}`, type });
       return clone;
    });
    if (onColSelect) onColSelect(null);
  };

  const layerColor = {
    bass:    '#60a5fa',
    melody:  '#34d399',
    perc:    '#fb923c',
  };

  // Chunk columns into rows
  const rows = useMemo(() => {
    const result = [];
    for (let i = 0; i < columns.length; i += COLUMNS_PER_ROW) {
      result.push(columns.slice(i, i + COLUMNS_PER_ROW));
    }
    return result;
  }, [columns]);

  const containerRef = useRef(null);

  // Auto-scroll playing column into view
  useEffect(() => {
    if (playingCol !== null && containerRef.current) {
      const activeEl = containerRef.current.querySelector(`[data-col-index="${playingCol}"]`);
      if (activeEl) {
        activeEl.scrollIntoView({ behavior: 'smooth', block: 'nearest', inline: 'center' });
      }
    }
  }, [playingCol]);

  if (columns.length === 0 && !editable) {
    return <div className="p-8 text-gray-500 italic text-center bg-[#11151c] rounded-xl border border-gray-800">No sequence available.</div>;
  }

  return (
    <div ref={containerRef} className="w-full flex flex-col space-y-12 bg-[#0d1117] p-2 overflow-x-hidden">
      {rows.map((rowCols, rowIndex) => (
        <div key={`row-${rowIndex}`} className="w-full bg-[#11151c] p-6 rounded-xl border border-gray-800 shadow-2xl relative overflow-hidden">
          <div className="min-w-max flex items-end">
             {/* Left axis labels */}
             <div className="flex flex-col font-mono text-gray-500 text-[15px] leading-loose pr-2 select-none border-r border-gray-800 mr-2 pt-[28px]">
                 <div className="text-yellow-500/80 font-bold">Perc|</div>
                 {strings.map(s => <div key={`axis-${rowIndex}-${s}`}>{tuningLabels[s]}|</div>)}
             </div>

             {/* Columns */}
             <div className="flex font-mono text-[#58a6ff] text-[15px] font-bold leading-loose tracking-widest pb-[2px]">
                {rowCols.map((col, idxInRow) => {
                   const index = rowIndex * COLUMNS_PER_ROW + idxInRow;

                   // ── BAR LINE RENDERING ──
                   if (col.type === 'barline') {
                     return (
                       <div key={col.id || `bar-${index}`} className="flex flex-col items-center select-none" style={{ width: '12px' }}>
                         <div className="h-7" /> {/* top spacer */}
                         <div className="text-gray-400 font-bold text-[13px]">|</div>
                         {strings.map(s => (
                           <div key={`bar-${index}-${s}`} className="h-[28px] flex items-center justify-center text-gray-400 font-bold text-[13px]">|</div>
                         ))}
                       </div>
                     );
                   }

                   // ── SPACER (rest/interval gap) ──
                   if (col.type === 'spacer' && (!col.notes || col.notes.length === 0)) {
                     return (
                       <div key={col.id || `spc-${index}`} className="flex flex-col items-center select-none opacity-30" style={{ width: '18px' }}>
                         <div className="h-7" />
                         <div className="text-gray-700">·</div>
                         {strings.map(s => (
                           <div key={`spc-${index}-${s}`} className="h-[28px] flex items-center justify-center text-gray-700">-</div>
                         ))}
                       </div>
                     );
                   }

                   let maxWidth = 3;
                   const cellRep = {};
                   let percRep = '';
                   
                   if (col.type === 'melody' || col.type === 'chord' || col.type === 'percussion' || col.type === 'spacer') {
                       strings.forEach(sIdx => {
                          const note = col.notes?.find(n => n.stringIdx === sIdx && !n.isPerc);
                          if (note) {
                            let chunk = `${note.fretIdx}`;
                            if (note.tech === '<>') chunk = `<${chunk}>`;
                            else if (note.tech === '()') chunk = `(${chunk})`;
                            if (note.techLabel) chunk = `${chunk}${note.techLabel}`;
                            cellRep[sIdx] = chunk;
                            if (chunk.length + 1 > maxWidth) maxWidth = chunk.length + 1;
                          }
                       });
                       const percs = col.notes?.filter(n => n.isPerc || n.stringIdx === 'perc');
                       if (percs && percs.length > 0) {
                          percRep = percs.map(p => {
                            if (p.tech === 'kick' || p.techLabel === 'K') return 'K';
                            if (p.tech === 'snare' || p.techLabel === 'S') return 'S';
                            return 'X';
                          }).join('+');
                          if (percRep.length + 1 > maxWidth) maxWidth = percRep.length + 1;
                       }
                   }

                   const isSelected = editable && activeCol === index;
                   const isPlayingNow = playingCol === index;
                   const confidence = confidenceScores[index];
                   const hasConfidence = confidence !== undefined;
                   const colOpacity = hasConfidence ? Math.max(0.35, confidence) : 1;

                   const hasPerc = col.notes?.some(n => n.isPerc);
                   const hasBass = col.notes?.some(n => !n.isPerc && typeof n.stringIdx === 'number' && n.stringIdx >= 3);
                   const hasMelody = col.notes?.some(n => !n.isPerc && typeof n.stringIdx === 'number' && n.stringIdx < 3);
                   
                   let layerHighlight = null;
                   if (activeLayer !== 'all') {
                     if (activeLayer === 'perc' && !hasPerc) layerHighlight = 'dim';
                     else if (activeLayer === 'bass' && !hasBass) layerHighlight = 'dim';
                     else if (activeLayer === 'melody' && !hasMelody) layerHighlight = 'dim';
                     else layerHighlight = activeLayer;
                   }

                   const layerBorderColor = layerHighlight && layerHighlight !== 'dim' ? layerColor[layerHighlight] : null;

                   return (
                      <div 
                        key={col.id || `fallback-${index}`}
                        data-col-index={index}
                        className={`relative flex flex-col items-center group transition-colors duration-100 rounded-sm
                          ${editable ? 'cursor-pointer hover:bg-[#58a6ff]/10' : ''}
                          ${isSelected ? 'bg-[#58a6ff]/20 outline outline-1 outline-[#58a6ff]' : ''}
                          ${isPlayingNow ? 'bg-green-500/20 outline outline-2 outline-green-400 shadow-[0_0_12px_rgba(74,222,128,0.3)]' : ''}
                        `}
                        style={{ opacity: layerHighlight === 'dim' ? 0.15 : colOpacity, borderBottom: layerBorderColor ? `2px solid ${layerBorderColor}` : undefined }}
                        onClick={() => editable && onColSelect && onColSelect(isSelected ? null : index)}
                      >
                         <div className="h-7 w-full flex items-end justify-center mb-0 overflow-visible whitespace-nowrap text-[12px] text-yellow-400 font-bold select-none px-2 tracking-normal">
                             {col.type === 'label' ? col.text : ''}
                         </div>
                         {hasConfidence && (
                           <div className="absolute -top-1 left-1/2 -translate-x-1/2 w-1.5 h-1.5 rounded-full z-10" style={{ background: confidence > 0.75 ? '#3fb950' : confidence > 0.5 ? '#e3b341' : '#f85149', boxShadow: `0 0 4px ${confidence > 0.75 ? '#3fb950' : '#e3b341'}` }} title={`Col Avg: ${Math.round(confidence * 100)}%`} />
                         )}
                         <div className="whitespace-pre text-yellow-500/80">
                             {(() => {
                               if (col.type === 'repeat_start') return '|:-';
                               if (col.type === 'repeat_end') return '-:|';
                               if (col.type === 'label') return '---';
                               const percs = col.notes?.filter(n => n.isPerc || n.stringIdx === 'perc') || [];
                               if (percs.length > 0) {
                                  const percText = percs.map(p => (p.tech === 'kick' || p.techLabel === 'K' ? 'K' : p.tech === 'snare' || p.techLabel === 'S' ? 'S' : 'X')).join('+');
                                  return <span className="px-1 bg-yellow-500/10 rounded border border-yellow-500/20 text-[10px] tracking-tight">{percText}</span>;
                               }
                               return '---';
                             })()}
                         </div>
                         {strings.map(sIdx => {
                             const cellNote = col.notes?.find(n => n.stringIdx === sIdx && !n.isPerc);
                             const isPlayable = !!cellNote && typeof cellNote.fretIdx === 'number';
                             const noteConf = cellNote?.normalized_confidence ?? cellNote?.raw_confidence;
                             const bgHighlight = noteConf && noteConf < 0.7 ? (noteConf < 0.4 ? 'bg-red-500/20 text-red-200' : 'bg-yellow-500/20 text-yellow-200') : '';

                             let noteContent = '-';
                             if (isPlayable) {
                               const fretStr = `${cellNote.fretIdx}`;
                               let displayStr = fretStr;
                               if (cellNote.tech === 'harmonic' || cellNote.tech === '<>') displayStr = `<${fretStr}>`;
                               else if (cellNote.tech === 'ghost' || cellNote.tech === '()') displayStr = `(${fretStr})`;

                               noteContent = (
                                 <div className="relative flex items-center justify-center min-w-[20px]">
                                   {(cellNote.tech === 'tap' || cellNote.tech === 'T') && <span className="absolute -top-3 text-[9px] text-blue-400">T</span>}
                                   <div className={`
                                      ${cellNote.tech === 'left_tap' || cellNote.tech === 'circle' ? 'border border-white/60 rounded-full px-1' : ''}
                                      ${bgHighlight}
                                      px-1 rounded-sm
                                   `}>
                                     {displayStr}
                                   </div>
                                 </div>
                               );
                             }

                             return (
                               <div key={`${index}-${sIdx}`} className={`h-[28px] flex items-center justify-center ${isPlayable ? 'cursor-pointer hover:text-green-300' : 'text-gray-700'}`} onClick={isPlayable ? async (e) => { e.stopPropagation(); await initAudio(); const midiNote = tuning[sIdx] + cellNote.fretIdx + capo; playNote(midiNote); } : undefined}>
                                 {noteContent}
                               </div>
                             );
                         })}
                         {editable && isSelected && (
                            <div className="absolute top-[110%] left-1/2 -translate-x-1/2 mt-2 z-50 bg-[#161b22] border border-[#58a6ff]/50 rounded-lg shadow-[0_4px_20px_rgba(0,0,0,0.8)] flex space-x-1 p-1 animate-fade-in" onClick={e => e.stopPropagation()}>
                               <button onClick={() => handleAddBefore(index)} className="p-2 hover:bg-[#58a6ff]/20 text-[#58a6ff] rounded"><svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 15l-3-3m0 0l3-3m-3 3h8M3 12a9 9 0 1118 0 9 9 0 01-18 0z" /></svg></button>
                               <button onClick={() => handleAddAfter(index)} className="p-2 hover:bg-[#58a6ff]/20 text-[#58a6ff] rounded"><svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 9l3 3m0 0l-3 3m3-3H8m13 0a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></button>
                               <button onClick={() => handleSetLabel(index)} className="p-2 hover:bg-yellow-500/20 text-yellow-400 rounded"><svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z" /></svg></button>
                               <button onClick={() => handleSetRepeat(index, 'repeat_start')} className="px-2 py-1 text-xs text-[#58a6ff] font-bold">|:</button>
                               <button onClick={() => handleSetRepeat(index, 'repeat_end')} className="px-2 py-1 text-xs text-[#58a6ff] font-bold">:|</button>
                               <button onClick={() => handleDelete(index)} className="p-2 hover:bg-red-500/20 text-red-400 rounded"><svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" /></svg></button>
                            </div>
                         )}
                      </div>
                   );
                })}
             </div>
             
             {/* Right axis */}
             <div className="flex flex-col font-mono text-gray-500 text-[15px] leading-loose pl-1 select-none pt-[28px]">
                 <div>|</div>
                 {strings.map(s => <div key={`axisend-${rowIndex}-${s}`}>|</div>)}
             </div>
          </div>
        </div>
      ))}
    </div>
  );
}
